# Generated by Django 4.2.3 on 2023-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_images/placeholder.jpg', upload_to='profile_images/%Y-%m-%d'),
        ),
    ]
