# Generated by Django 4.2.3 on 2023-09-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
